### PR TITLE
添加注释

### PR DESCRIPTION
**Pull request by yonghuming**
添加注释

### CODE REVIEW

**Comment by yonghuming** [comment]
最近想写一个五子棋,没有思路所以在这里搜了一下代码,看到了你的实现,很巧妙,看的过程中顺便写了注释

**Comment by Jamesxu182** [comment]
亲爱的开发者

我写了一个AI的五子棋软件，我可以提供我的软件的源码给你。去过你愿意给我邮箱的话。

Yifan

**Comment by yonghuming** [comment]
亲爱的Yifan:
我的邮箱是964683112@qq.com
langxm682

**Comment by Jamesxu182** [comment]
Dear Developer

It is really shame that I can't find the source code of AI Gomoku that I wrote before, I am sorry for that. but I could provide some advice to you. you could search "Gomoku Algorithm" online and there are two kind of algorithms commonly being used. 

I just used one of the algorithms and implement it with python one year before, and it is not too hard. I attached the link below and hope you could understand.

<a>http://www.kuqin.com/algorithm/20080313/4483.html</a>

This is the algorithm I used before.

By the way, thank you for your comment. Good luck in your coding.

Best Regards
Yifan

**Comment by yonghuming** [comment]
Dear Developer
Thank you very much.i'll take your advice.i will try. and i found that Gomoku also called gobang,i found your pragraming is very helpfull for me to develop other chess-like games, it's struction are very easy to understand . i learned a lot from your code . and i have find another Gomoku program on github that implement AI,i want to combine your work .
Thank you very much.Thank you for your work.
Best Regards
langxm682

**Comment by yonghuming** [comment]
I find i list of Abstract strategy game on wik ihttps://en.wikipedia.org/wiki/Abstract_strategy_game and here https://zh.wikipedia.org/wiki/%E6%8A%BD%E8%B1%A1%E7%AD%96%E7%95%A5%E9%81%8A%E6%88%B2%E5%88%97%E8%A1%A8
the chinese version wiki lists a lot of abstract strategy game and i want to implement them, if things goes well ,i will try to let's boys play them

**Pull request merged**
